EconomySheetUpdater/Controllers/OverviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using EconomySheetUpdater.Models;
using Google.Apis.Auth.OAuth2.Mvc;
using Google.Apis.Sample.MVC4;

namespace EconomySheetUpdater.Controllers
{
    public class OverviewController : Controller
    {
        //
        // GET: /Overview/

        public ActionResult IndexHelper()
        {
            return new RedirectResult("Index");
        }

        public async Task<ActionResult> Index(int WsId = -1)
        {
            var result = await new AuthorizationCodeMvcApp(this, new AppFlowMetadata()).
           AuthorizeAsync(new CancellationToken(false));
            if (result.Credential != null)
            {
                SpreadSheetHelper.setFactory(result.Credential.Token.AccessToken);

            }
            var model = new OverviewModel().GetModel(WsId);
            if (model.initfailed)
            {
                return RedirectToAction("Failed");
            }
            return View(model);
        }
        public ActionResult Failed()
        {
            return View("../Failed/Index");
        }
    }
}

EconomySheetUpdater/Views/Failed/Index.cshtml
@using EconomySheetUpdater.Models
@model OverviewModel
@{
    var mod = new OverviewModel().GetModel(-1);
    ViewBag.Title = "Failed";
}

<h2 class="red">Failed</h2>
@using (@Html.BeginForm("Index", "Overview", FormMethod.Get, new { id = "ddForm" })){
@Html.DropDownListFor(ws => ws.WsId, mod.OtherWorksheets, "This Month" ,new {id="ddWs",onchange="this.form.submit()"})
}
<p>
    Something went wrong when fetching the spreadsheet. You can try to select a different month or try and fix the problem directly in the <a href="https://docs.google.com/spreadsheet/ccc?key=0AkyjIQHybNeidEhVOGY2WlBnSld2Y1JnaUdxeUcweEE&usp=sharing#gid=35">spreadsheet.</a>
</p>